# Jekyll configuration

name: Radical Documentation
description: ''

# url is currently only used only for the RSS feed in feed.xml
# url: http://scotte.github.io
baseurl: /documentation

# This can be '' to hide the Github nav button
github: 'radicalfx/documentation'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: false

permalink: /:categories/:title
# paginate: 3

# pygments requires pyton, gh pages seems to only like pygments, so on Windows pyton is required.
highlighter: pygments

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']