version: '{build}'
image: Visual Studio 2019

skip_branch_with_pr: true
pull_requests:
  do_not_increment_build_number: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
  - master
  - /release-.*/
  - /^\d+\.\d+\.\d+(-\S*)?$/

skip_tags: false
configuration: Release
platform: Any CPU

before_build:
  - 'nuget restore .\src\samples\Modules\Modules.sln'
  - 'nuget restore .\src\samples\Plugins\Plugins.sln'
  - 'nuget restore .\src\samples\Showcases\Showcases.sln'

build_script:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.com" .\src\samples\Modules\Modules.sln /Build Release'
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.com" .\src\samples\Plugins\Plugins.sln /Build Release'
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.com" .\src\samples\Showcases\Showcases /Build Release'

deploy: off