version: '{build}'
image: Visual Studio 2022

skip_branch_with_pr: true
pull_requests:
  do_not_increment_build_number: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
  - master
  - /release-.*/
  - /^\d+\.\d+\.\d+(-\S*)?$/

skip_tags: false
configuration: Release
platform: Any CPU

before_build:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe'

build_script:
  - 'msbuild .\samples\Modules\Modules.sln /t:Restore /p:Configuration=Release'
  - 'msbuild .\samples\Modules\Modules.sln /p:Configuration=Release'
  - 'msbuild .\samples\Plugins\Plugins.sln /t:Restore /p:Configuration=Release'
  - 'msbuild .\samples\Plugins\Plugins.sln /p:Configuration=Release'
  - 'msbuild .\samples\Showcases\Showcases.sln /t:Restore /p:Configuration=Release'
  - 'msbuild .\samples\Showcases\Showcases.sln /p:Configuration=Release'
  - 'msbuild .\samples\AutocompleteSample\AutocompleteSample.sln /t:Restore /p:Configuration=Release'
  - 'msbuild .\samples\AutocompleteSample\AutocompleteSample.sln /p:Configuration=Release'

deploy: off
