site_name: Radical Framework Documentation
repo_url: https://github.com/RadicalFx/documentation/
site_author: The Radical team
remote_branch: master
theme: bootstrap

pages:
- 'Home': 'README.md'
- 'How To': 'how-tos/index.md'
- 'Presentation':
    - 'AbstractViewModel': 'mvvm/abstract-view-model.md'
    - 'Conventions':
        - 'Conventions': 'mvvm/conventions.md'
        - 'Bootstrap Conventions': 'mvvm/bootstrap-conventions.md'
        - 'Runtime Conventions': 'mvvm/runtime-conventions.md'
        - 'Conventions override': 'mvvm/conventions-override.md'
    - 'Commands and DelegateCommand': 'mvvm/delegate-command.md'
    - 'Message broker MVVM built-in messages': 'mvvm/built-in-messages.md'
    - 'Application boot process demystified':
        - 'Boot process': 'mvvm/boot-process-demystified.md'
        - 'Application shutdown': 'mvvm/application-shutdown.md'
        - 'Singleton applications': 'mvvm/singleton-applications.md'