site_name: Radical Framework Documentation
repo_url: https://github.com/RadicalFx/documentation/
site_author: The Radical team
remote_branch: master

pages:
- 'Home': 'README.md'
- 'How To': 'how-tos/index.md'
- 'Presentation':
    - 'AbstractViewModel': 'mvvm/abstract-view-model.md'
    - 'Conventions':
        - 'Conventions': 'mvvm/conventions.md'
        - 'Bootstrap Conventions': 'mvvm/bootstrap-conventions.md'
        - 'Runtime Conventions': 'mvvm/runtime-conventions.md'
        - 'Conventions override': 'mvvm/conventions-override.md'
    - 'Commands and DelegateCommand': 'mvvm/delegate-command.md'
    - 'Message broker MVVM built-in messages': 'mvvm/built-in-messages.md'
    - 'Application boot process demystified':
        - 'Boot process': 'mvvm/boot-process-demystified.md'
        - 'Application shutdown': 'mvvm/application-shutdown.md'
        - 'Singleton applications': 'mvvm/singleton-applications.md'
- 'UI Composition':
    - 'UI Composition': 'ui-composition/index.md'
    - 'Region content lifecycle': 'ui-composition/region-content-lifecycle.md'
    - 'TabControl region': 'ui-composition/tabcontrol-region.md'
    - 'Create a custom region': 'ui-composition/create-a-custom-region.md'
- 'Concepts':
    - 'Inversion of Control':
        - 'Introduction': 'ioc/index.md'    
        - 'Castle Windsor': 'ioc/windsor.md'
        - 'Autofac': 'ioc/autofac.md'
        - 'Unity': 'ioc/unity.md'
        - 'Puzzle Container': 'ioc/puzzle.md'
    - 'Entities':
        - 'Property System': 'entities/property-system.md'
    - 'Messaging and Message Broker':
        - 'Message Broker': 'messaging/message-broker.md'
        - 'POCO messages': 'messaging/poco-messages.md'
        - 'Standalone message handlers': 'messaging/abstract-message-handler.md'
    - 'Observers':
        - 'Introduction': 'observers/index.md'
        - 'PropertyObserver': 'observers/property-observer.md'
        - 'MementoObserver': 'observers/memento-observer.md'
        - 'BrokerObserver': 'observers/broker-observer.md'
- 'Memento':
    - 'Change Tracking Service':
        - 'Introduction': 'memento/change-tracking-service.md'
        - 'MementoEntity and MementoEntityCollection': 'memento/memento-entities.md'
        - 'Handling change tracking':
            - 'Simple model': 'memento/simple-model.md'
            - 'Collections': 'memento/collections.md'
            - 'Complex objects graph': 'memento/complex-graph.md'
        - 'Atomic operations': 'memento/atomic-operations.md'
        - 'Change Tracking Service API': 'memento/change-tracking-service-api.md'
        - 'Property Metadata for the Change Tracking Service': 'memento/memento-metadata.md'
        - 'Handling collection sync': 'memento/handling-collection-sync.md'