version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/samples/Modules"
    update_schedule: "live"
  - package_manager: "dotnet:nuget"
    directory: "/samples/Plugins"
    update_schedule: "live"
  - package_manager: "dotnet:nuget"
    directory: "/samples/Showcases"
    update_schedule: "live"
