version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/samples/Modules"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
  - package_manager: "dotnet:nuget"
    directory: "/samples/Plugins"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
  - package_manager: "dotnet:nuget"
    directory: "/samples/Showcases"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
